### ISSUE TITLE
OS.js stuck at loading the hardware service provider

### ISSUE THREAD

**Issue by SpaceboyRoss01** [BlueLightOS/bluelight#6]
**Details**
- [x] Virtual Machine: VirtualBox 6.0.0
- Motherboard: VirtualBox PIIX3
- BIOS Ver: VirtualBox
- CPU: VirtualBox
- Disk (**/dev/sda**): 8GB
- OS Version: `0.1.8-prealpha`

**Describe the bug**
After the bootsplash screen starts, there's just a black screen.

**To Reproduce**
1. Boot the operating system

**Expected behavior**
OS.js to load

**Comment by SpaceboyRoss01** [comment]
```
[osjs@osjs ~]$ tail -f /proc/797/fd/1

[core] › …  awaiting                     Initializing core
[core] › …  awaiting                     Initializing providers
[core] › ℹ  info                         Provider binding osjs/express
[core] › ▶  start                        Starting server
[core] › ℹ  info                         Using package discovery file /opt/os.js/packages.json
[core] › ℹ  info                         Using package manifest file /opt/os.js/dist/metadata.json
[core] › ℹ  info                         Provider binding osjs/packages
[core] › ℹ  info                         Provider binding osjs/vfs
[core] › ℹ  info                         Provider binding hw
```
Tailing the OS.js `npm run serve` process shows that OS.js is stuck at loading. @andersevenrud will have to help with this.

**Comment by SpaceboyRoss01** [comment]
Killing the `npm run serve` process and manually starting OS.js results in this output:
```
[osjs@osjs os.js]$ npm run serve

> @osjs/osjs@3.0.0-alpha.29 serve /opt/os.js
> node src/server/index.js

[core] › …  awaiting  Initializing core
[core] › …  awaiting  Initializing providers
[core] › ℹ  info      Provider binding osjs/express
[core] › ▶  start     Starting server
[core] › ℹ  info      Using package discovery file /opt/os.js/packages.json
[core] › ℹ  info      Using package manifest file /opt/os.js/dist/metadata.json
[core] › ℹ  info      Provider binding osjs/packages
[core] › ℹ  info      Provider binding osjs/vfs
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
TypeError: entry.isFile is not a function
    at EntryFilter.onlyFileFilter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:56:49)
    at EntryFilter.filter (/opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:32:18)
    at /opt/os.js/node_modules/fast-glob/out/providers/filters/entry.js:18:48
    at /opt/os.js/node_modules/fast-glob/out/adapters/fs-stream.js:33:39
[core] › ℹ  info      Provider binding hw
```

**Comment by SpaceboyRoss01** [comment]
I discovered this https://github.com/mrmlnc/fast-glob/issues/144

**Comment by SpaceboyRoss01** [comment]
Fixed
